### ISSUE TITLE
Error en data.csv

### ISSUE THREAD

**Issue by leytzher** [rafnixg/covid-19_latinoamerica_api#3]
etl.py genera una columna extra en data.csv (llamada 404: Not Found). 
`
ISO 3166-2 Code,Province/State,Country/Region,Date,Confirmed,Deaths,Recovered,404: Not Found
AR-C,Ciudad Autonoma de Buenos Aires,Argentina,2020-02-25,0.0,0.0,0,
AR-B,Buenos Aires,Argentina,2020-02-25,0.0,0.0,0,
AR-K,Catamarca,Argentina,2020-02-25,0.0,0.0,0,
AR-H,Chaco,Argentina,2020-02-25,0.0,0.0,0,
`
Esta columna no tiene ningun valor asignado y por lo tanto genera NaN's en pandas.

**Comment by rafnixg** [comment]
Mas tarde reviso y subo el FIX.

**Comment by rafnixg** [comment]
@leytzher Subi ajustes al ETL, normaliza la data y ya no muestra el 404: Not Found.
