### ISSUE TITLE
Api doesn't work

### ISSUE THREAD

**Issue by edsonvargas** [rafnixg/covid-19_latinoamerica_api#9]
Hi, this is Edson, just want to report an application error. For example, when i try to call this uri, https://covid19latam.herokuapp.com/paises-disponibles, i don't receive any response.

Thanks.

**Comment by rafnixg** [comment]
Hi @edsonvargas, thanks for reporting this issue, to deploy this API I'm using Heroku free dynos which makes the API performance affected.

The API is now active!
